using Regira.Media.Drawing.Dimensions;
using Regira.Media.Drawing.Utilities;

namespace Drawing.Testing;

[TestFixture]
public class DimensionTests
{
    // generated by GitHub Copilot

    [Test]
    public void CalculateSize_FromPoints_ReturnsCorrectSize()
    {
        var topLeft = new ImagePoint(10, 20);
        var bottomRight = new ImagePoint(30, 50);
        var expected = new ImageSize(20, 30);
        var result = DrawImageUtility.CalculateSize(topLeft, bottomRight);
        Assert.That(result.Width, Is.EqualTo(expected.Width));
        Assert.That(result.Height, Is.EqualTo(expected.Height));
    }

    [Test]
    public void CalculateSize_ScaleToFit_ReturnsCorrectScaledSize()
    {
        var source = new ImageSize(200, 100);
        var target = new ImageSize(100, 100);
        var expected = new ImageSize(100, 50);
        var result = DrawImageUtility.CalculateSize(source, target);
        Assert.That(result.Width, Is.EqualTo(expected.Width));
        Assert.That(result.Height, Is.EqualTo(expected.Height));
    }

    [Test]
    public void ToPoints_ReturnsCorrectPoints()
    {
        var position = new ImageEdgeOffset(10, 20, 5, 15);
        var totalSize = new ImageSize(100, 200);
        var (topLeft, bottomRight) = DrawImageUtility.ToPoints(position, totalSize);
        Assert.That(topLeft.X, Is.EqualTo(20));
        Assert.That(topLeft.Y, Is.EqualTo(10));
        Assert.That(bottomRight.X, Is.EqualTo(85));
        Assert.That(bottomRight.Y, Is.EqualTo(195));
    }

    [Test]
    public void ToPointSize_ReturnsCorrectPointAndSize()
    {
        var position = new ImageEdgeOffset(10, 20, 5, 15);
        var totalSize = new ImageSize(100, 200);
        var (coordinate, size) = DrawImageUtility.ToPointSize(position, totalSize);
        Assert.That(coordinate.X, Is.EqualTo(20));
        Assert.That(coordinate.Y, Is.EqualTo(10));
        Assert.That(size.Width, Is.EqualTo(65));
        Assert.That(size.Height, Is.EqualTo(185));
    }

    [Test]
    public void ToPosition_ReturnsCorrectPosition()
    {
        var topLeft = new ImagePoint(20, 10);
        var bottomRight = new ImagePoint(85, 195);
        var totalSize = new ImageSize(100, 200);
        var pos = DrawImageUtility.ToOffset(topLeft, bottomRight, totalSize);
        Assert.That(pos.Top, Is.EqualTo(10));
        Assert.That(pos.Left, Is.EqualTo(20));
        Assert.That(pos.Bottom, Is.EqualTo(5));
        Assert.That(pos.Right, Is.EqualTo(15));
    }
}